## Date: 06/02/2023

Importing the Dependencies

In [1]:
import numpy as np
import pandas as pd

import sklearn
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [2]:
print("numpy version: ", np.__version__)
print("pandas version: ", pd.__version__)
print("sklearn version: ", sklearn.__version__)


# numpy version:  1.24.1
# pandas version:  1.5.2
# sklearn version:  1.2.1

numpy version:  1.24.1
pandas version:  1.5.2
sklearn version:  1.2.1


Data Collection and Processing

In [3]:
# loading dataset

df = pd.read_csv("dataset/heart.csv")

In [4]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [5]:
# number of rows and columns in the dataset

df.shape

(303, 14)

In [6]:
# checking for missing values

df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [7]:
# checking the distribution of Target Variable

df['target'].value_counts()

1    165
0    138
Name: target, dtype: int64

1 --> Defective Heart

0 --> Healthy Heart

Splitting the Features and Target

In [8]:
X = df.drop(columns='target', axis=1)

y = df['target']

In [9]:
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [10]:
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

### **Train Test Split**

In [11]:
# Here, stratify parameter used so that our target class is divide equally for botho training and test sample

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=3)

In [12]:
print(X.shape, X_train.shape, X_test.shape)

(303, 13) (242, 13) (61, 13)


## Comparing the performance of the models

In [13]:
# list of models

models = [LogisticRegression(max_iter=1000), SVC(kernel='linear'), KNeighborsClassifier(), RandomForestClassifier()]

In [14]:
def compare_models_train_test():
    
    for model in models:
        # training the model
        model.fit(X=X_train, y=y_train)
    
        # evaluating the model
        y_pred = model.predict(X=X_test)

        accuracy = accuracy_score(y_true=y_test, y_pred=y_pred)

        print('Accuracy score of the ', model, ' = ', accuracy)


In [15]:
compare_models_train_test()

Accuracy score of the  LogisticRegression(max_iter=1000)  =  0.7704918032786885
Accuracy score of the  SVC(kernel='linear')  =  0.7704918032786885
Accuracy score of the  KNeighborsClassifier()  =  0.6557377049180327
Accuracy score of the  RandomForestClassifier()  =  0.7704918032786885


## Apply CrossValidation

doc: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html#sklearn.model_selection.cross_val_score

### Logistic Regression

In [16]:
cv_score_lr = cross_val_score(estimator=LogisticRegression(max_iter=1000), X=X, y=y, cv=5)

print(cv_score_lr)

mean_accuracy_lr = sum(cv_score_lr) / len(cv_score_lr)

mean_accuracy_lr = mean_accuracy_lr * 100

mean_accuracy_lr = round(mean_accuracy_lr, 2)

print(mean_accuracy_lr)

[0.80327869 0.86885246 0.85245902 0.86666667 0.75      ]
82.83


### Support Vector Classifier

In [17]:
cv_score_svc = cross_val_score(estimator=SVC(kernel='linear'), X=X, y=y, cv=5)

print(cv_score_svc)

mean_accuracy_svc = sum(cv_score_svc)/len(cv_score_svc)

mean_accuracy_svc = mean_accuracy_svc*100

mean_accuracy_svc = round(mean_accuracy_svc, 2)

print(mean_accuracy_svc)

[0.81967213 0.8852459  0.80327869 0.86666667 0.76666667]
82.83


### Creating a Function to compare the models

In [18]:
# list of models

models = [LogisticRegression(max_iter=1000), SVC(kernel='linear'), KNeighborsClassifier(), RandomForestClassifier()]

In [19]:
def compare_models_cross_validation():
    
    for model in models:
        
        cv_score = cross_val_score(estimator=model, X=X, y=y, cv=5)

        mean_accuracy = sum(cv_score) / len(cv_score)

        mean_accuracy = mean_accuracy * 100

        mean_accuracy = round(mean_accuracy, 2)

        print('Cross Validation accuracies for ', model, '=  ', cv_score)
        print('Accuracy % of the ', model, "=", mean_accuracy)
        print('----------------------------------------------')


In [20]:
compare_models_cross_validation()

Cross Validation accuracies for  LogisticRegression(max_iter=1000) =   [0.80327869 0.86885246 0.85245902 0.86666667 0.75      ]
Accuracy % of the  LogisticRegression(max_iter=1000) = 82.83
----------------------------------------------
Cross Validation accuracies for  SVC(kernel='linear') =   [0.81967213 0.8852459  0.80327869 0.86666667 0.76666667]
Accuracy % of the  SVC(kernel='linear') = 82.83
----------------------------------------------
Cross Validation accuracies for  KNeighborsClassifier() =   [0.60655738 0.6557377  0.57377049 0.73333333 0.65      ]
Accuracy % of the  KNeighborsClassifier() = 64.39
----------------------------------------------
Cross Validation accuracies for  RandomForestClassifier() =   [0.83606557 0.86885246 0.81967213 0.83333333 0.78333333]
Accuracy % of the  RandomForestClassifier() = 82.83
----------------------------------------------


Doc: https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter

In [21]:
cross_val_score(estimator=RandomForestClassifier(), X=X, y=y, scoring="accuracy", cv=5)

array([0.85245902, 0.86885246, 0.7704918 , 0.8       , 0.75      ])

In [22]:
cross_val_score(estimator=RandomForestClassifier(), X=X, y=y, scoring="average_precision", cv=5)

array([0.82196268, 0.96033569, 0.88330127, 0.93065767, 0.86385466])